function [flNError, flNFit, falCurve] = ...
    calcErrorTRSS2017ForceLengthRelationAscendingLimb(...
        paramArg, expLce,expFlN, ...
        sarcomereProperties,...
        musculotendonProperties,...
        flag_compensateForCrossbridgeStiffness)

expLceN = expLce/musculotendonProperties.optimalFiberLength;

adjustAscendingLimbNormalizedForce      = paramArg(1,1);
useRoundAscendingLimb                   = 0;

%flag_compensateForCrossbridgeStiffness              = 0;
curvinessActiveForceLength                          = 0.5;
shiftLengthActiveForceLengthCurveDescendingCurve    = 0;
smallNumericallyNonZeroNumber                       = sqrt(sqrt(eps));

flag_enableNumericallyNonZeroGradients              =1;
flag_useOctave                                      = 0;

[falCurve, ...
  activeForceLengthCurveAnnotationPoints] ...
    = createFiberActiveForceLengthCurve2025(...
          sarcomereProperties.normMyosinHalfLength*2,...
          sarcomereProperties.normMyosinBareHalfLength*2,...
          sarcomereProperties.normActinLength,...
          sarcomereProperties.normZLineLength,...
          sarcomereProperties.normSarcomereLengthZeroForce,...
          sarcomereProperties.normCrossBridgeStiffness,...          
          curvinessActiveForceLength, ...           
          shiftLengthActiveForceLengthCurveDescendingCurve,...
          adjustAscendingLimbNormalizedForce,...
          useRoundAscendingLimb,...
          flag_compensateForCrossbridgeStiffness,...          
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          'fl',...
          flag_useOctave);  

flNError = zeros(length(expLceN),1);
flNFit = flNError;
for i=1:1:length(expLceN)
    flN = calcBezierYFcnXDerivative(expLceN(i),falCurve,0);
    flNFit(i,1)=flN;
    flNError(i,:) = (expFlN(i,1)-flN);
end