function [fvNError, fvCurve] = ...
    calcErrorTRSS2017ForceVelocityRelation(...
        paramArg, expfv, ...
        falCurve,...
        musculotendonProperties)


fvNvEccLow = musculotendonProperties.forceVelocityMultiplierAtLowEccentricFiberVelocity ...
            + paramArg(1,1);

fvNvEccMax = musculotendonProperties.forceVelocityMultiplierAtMaximumEccentricFiberVelocity ...
            + paramArg(1,1);

useSharpForceVelocityCurve=1;
flag_enableNumericallyNonZeroGradients=1;
smallNumericallyNonZeroNumber=sqrt(sqrt(eps));
flag_useOctave=1;

%
% This needs to match curves/createFittedMuscleCurvesTRSS2017.m
%   lines 243-274
%

curvinessEccentricForceVelocity = 0.9;



if(useSharpForceVelocityCurve==1)

    dydxEcc_div_dydxConc = 5;
    %dydxEcc_div_dydxConc = 10;
    curvinessEccentricForceVelocitySharp = 0.95;
    
    fvCurve ...
      = createFiberForceVelocitySharpCurve(...
          musculotendonProperties.forceVelocityMultiplierAtHalfMaximumFiberVelocity,...
          fvNvEccLow,...
          fvNvEccMax,...
          curvinessEccentricForceVelocitySharp,...
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          'fv',...
          dydxEcc_div_dydxConc,...
          flag_useOctave);

else
    fvCurve ...
      = createFiberForceVelocityCurve(...
          musculotendonProperties.forceVelocityMultiplierAtHalfMaximumFiberVelocity,...
          fvNvEccLow,...
          fvNvEccMax,...
          curvinessEccentricForceVelocity,...
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          'fv',...
          flag_useOctave);
end



fvNErrorV = zeros(length(expfv.fvN),1);
for i=1:1:length(expfv.lceN)
    flN = calcBezierYFcnXDerivative(expfv.lceN(i),falCurve,0);
    fvN = calcBezierYFcnXDerivative(expfv.vceN(i),fvCurve,0);
    fvNErrorV(i,:) = (expfv.fN(i,1)-flN*fvN);
end

fvNError = sqrt(mean(fvNErrorV.^2));